### ISSUE TITLE
name FakeUserAgentError is not defined

### ISSUE THREAD

**Issue by largyschool** [vinaywadhwa/justwatch-alfred#12]
Mac OSx 13.0.1 (Ventura)

Alfred 5.0.6 (2110)
Workflow v1.1.2

# python3 main.py -i GB -s loving > justwatch_error.txt 2>&1

gives the output enclosed in the attached file.

Perhaps, this could be linked to this change in Ventura OS?: https://www.alfredforum.com/topic/18184-alfred-cannot-find-files-after-installing-dropbox-beta-for-cloudstorage-intel/page/2/#comments
[justwatch_error.txt](https://github.com/vinaywadhwa/justwatch-alfred/files/10299159/justwatch_error.txt)

**Comment by ccarpiog** [comment]
Same FakeUserAgentError here. macOS Ventura 13.2 beta (22D5038i)

**Comment by philmnoir** [comment]
Also experiencing the "name 'FakeUserAgentError' is not defined" error.

Mac OSX 10.15.7 (Catalina)
[Just Watch Alfred Workflow error.txt](https://github.com/vinaywadhwa/justwatch-alfred/files/10452330/Just.Watch.Alfred.Workflow.error.txt)

Alfred 5.0.6
Workflow v1.1.2

[Debugger text attached]

[Just Watch Alfred Workflow error.txt](https://github.com/vinaywadhwa/justwatch-alfred/files/10452331/Just.Watch.Alfred.Workflow.error.txt)

**Comment by vinaywadhwa** [comment]
Thanks for the report! This is fixed and a new version is out (1.1.3). Cheers!

**Comment by philmnoir** [comment]
Thank you for looking into this Vinay. I continue to experience an error
related to a missing module called "importlib_resources". Appreciate your
work developing this. Do you have a Patreon?

P.

**Comment by vinaywadhwa** [comment]
@philmnoir strange! Would you mind creating another issue for this, since it seems like a different error? I will take a look.

[Patreon](patreon.com/vinayw) 🍻
