### ISSUE TITLE
Python 3 compatibility - cPickle

### ISSUE THREAD

**Issue by Goldsucher** [vinaywadhwa/justwatch-alfred#8]
Hi,

since macOS 12.3 (which removed python 2) the workflow isn't working anymore. Module cPickle is missing:

ModuleNotFoundError: No module named 'cPickle'

would be happy if this could be fixed 😊

**Comment by vinaywadhwa1** [comment]
Hello, 
Thanks for the report. I haven't managed to get my hands on on 12.3 yet so it'll be a bit tricky to fix it before that, sorry, unless - someone helps out with a PR.

**Comment by vinaywadhwa** [comment]
Hello,
Thanks for the report. I haven't managed to get my hands on 12.3 yet so it'll be a bit tricky to fix it before that, sorry, unless - someone helps out with a PR.

**Comment by vinaywadhwa** [comment]
Hey @Goldsucher : I've managed to attempt a fix for the newer mac OS versions, with python 3 support. Would you be kind enough to test the [updated version](https://github.com/vinaywadhwa/justwatch-alfred/raw/master/JustWatch%20-%20Alfred%20-%20v1.1.0.alfredworkflow) and let me know if it works for you?

**Comment by Goldsucher** [comment]
Hi @vinaywadhwa 
thanks for the update! Tried it but unfortunately I still get an error. 

`[23:52:00.963] JustWatch - Alfred[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.B2A869F2-13C7-4253-90A0-61A1FEB722F4%3E50B0CD10-4D52-4898-9C05-DD3A34A829C3)] Queuing argument 'modern family'
[23:52:00.995] JustWatch - Alfred[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.B2A869F2-13C7-4253-90A0-61A1FEB722F4%3E50B0CD10-4D52-4898-9C05-DD3A34A829C3)] Script with argv '(null)' finished
[23:52:01.004] ERROR: JustWatch - Alfred[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.B2A869F2-13C7-4253-90A0-61A1FEB722F4%3E50B0CD10-4D52-4898-9C05-DD3A34A829C3)] Code 127: /bin/bash: /usr/bin/python: No such file or directory`

But it could be possible, that my python installation is basically broken. It is located at usr/local/bin/python but changing it in the scripts did't help.

**Comment by vinaywadhwa** [comment]
@Goldsucher 
oops! I'm curious as to why the error still shows `/usr/bin/python: No such file or directory` when I've updated the command to `/usr/bin/python3`

![Screenshot 2022-06-08 at 14 53 41](https://user-images.githubusercontent.com/5197729/172581816-f93e770f-7951-44ab-aab1-a172a02054d2.png)

Are you sure you uninstalled the old workflow and reinstalled the [new one](https://github.com/vinaywadhwa/justwatch-alfred/raw/master/JustWatch%20-%20Alfred%20-%20v1.1.0.alfredworkflow)? If you did install the new version, the next course of action is for me to get some clarity on the python bundling situation.

I need to find out : 
- **if MacOs 12.3 and beyond do come packaged with python3 installed** - or there's no python installed at all ... I assumed it to be the former from what I read and experienced - but I may have installed python3 manually but I can't remember  ... I have no way to know other than reinstalling the OS, which I would want to obviously avoid.
- I also suspect installing Alfred also leads to a python3 install - If it does, we should be good. Again, no quick way to check this. 

Do you happen to know answers to either of these? I'll also ask on the Alfred forum if you confirm you're using the correct workflow version.

**Comment by Goldsucher** [comment]
@vinaywadhwa ah sorry my fault! I picked the latest release from your repo. Sorry for the confusion. 
With your linked workflow it works but in the providers script filter I think you forgot the "3" at `/usr/bin/python3`
After I added it, it works!

- Yes I am pretty sure that python is not delivered with MacOS anymore. Python2 was removed and Python3 was never delivered. 
- I am not sure but I think python is not installed with Alfred installation. And I have no idea how to face that problem. 

I think it's a good idea to ask on the Alfred forum.

Thanks again for your investigation!

**Comment by vinaywadhwa** [comment]
Ah, okay .. glad it works. Thanks for checking.
I've fixed everything and made a new release (1.1.0). 

I did post on the forums. Let's see if the Alfred mods have any suggestions to make the workflow work for everyone with Alfred on newer MacOS versions. Will keep this issue open for a while.

**Comment by vitorgalvao** [comment]
For completeness, posting a [link to the forum answer](https://www.alfredforum.com/topic/14853-justwatch-alfred-workflow/?do=findComment&comment=95731) explaining the `/usr/bin/python3` situation on macOS.

**Comment by vinaywadhwa** [comment]
this was fixed in [1.1.1](https://github.com/vinaywadhwa/justwatch-alfred/releases/tag/1.1.1)
